#pragma once

#include "superglue.h"

#define AGL_SAMPLER_TEXTURE0 (GL_TEXTURE0 - GL_TEXTURE0)
#define AGL_SAMPLER_TEXTURE1 (AGL_SAMPLER_TEXTURE0 + 1)
#define AGL_SAMPLER_TEXTURE2 (AGL_SAMPLER_TEXTURE0 + 2)
#define AGL_SAMPLER_TEXTURE3 (AGL_SAMPLER_TEXTURE0 + 3)
#define AGL_SAMPLER_TEXTURE4 (AGL_SAMPLER_TEXTURE0 + 4)
#define AGL_SAMPLER_TEXTURE5 (AGL_SAMPLER_TEXTURE0 + 5)
#define AGL_SAMPLER_TEXTURE6 (AGL_SAMPLER_TEXTURE0 + 6)
#define AGL_SAMPLER_TEXTURE7 (AGL_SAMPLER_TEXTURE0 + 7)
#define AGL_SAMPLER_TEXTURE8 (AGL_SAMPLER_TEXTURE0 + 8)
#define AGL_SAMPLER_TEXTURE9 (AGL_SAMPLER_TEXTURE0 + 9)
#define AGL_SAMPLER_TEXTURE10 (AGL_SAMPLER_TEXTURE0 + 10)
#define AGL_SAMPLER_TEXTURE11 (AGL_SAMPLER_TEXTURE0 + 11)
#define AGL_SAMPLER_TEXTURE12 (AGL_SAMPLER_TEXTURE0 + 12)
#define AGL_SAMPLER_TEXTURE13 (AGL_SAMPLER_TEXTURE0 + 13)
#define AGL_SAMPLER_TEXTURE14 (AGL_SAMPLER_TEXTURE0 + 14)
#define AGL_SAMPLER_TEXTURE15 (AGL_SAMPLER_TEXTURE0 + 15)
